# Generated by Django 6.0.3 on 2026-03-09 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(help_text='Poll ka sawal likhein', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Thoda context ya description poll ke liye (Optional)', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Keval ek poll ko active rakhein jo frontend par dikhega')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(help_text='Option ka naam', max_length=255)),
                ('votes', models.IntegerField(default=0, help_text='Total votes received')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='interactions.poll')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
