version: '3.8'

services:
  # PostgreSQL Database Container
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: newshub_db
      POSTGRES_USER: newshub_user
      POSTGRES_PASSWORD: newshub_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build:
      context: . # Ab current directory hi news-backend hai
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: newshub_db
      POSTGRES_USER: newshub_user
      POSTGRES_PASSWORD: newshub_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis

  celery:
    build:
      context: . # Ab current directory hi news-backend hai
      dockerfile: Dockerfile
    command: celery -A newshub_core worker --loglevel=info
    restart: always
    environment:
      POSTGRES_DB: newshub_db
      POSTGRES_USER: newshub_user
      POSTGRES_PASSWORD: newshub_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - media_volume:/app/media
    depends_on:
      - db
      - redis
      - backend

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80" # Bahar se localhost:8000 hit karne par request Nginx par aayegi
    volumes:
      # Nginx config ab news-backend ke andar wale nginx folder se uthayega
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
  postgres_data: