# Generated by Django 6.0.3 on 2026-03-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mobile_only', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
                ('title', models.CharField(help_text='Internal reference ke liye naam', max_length=150)),
                ('slot', models.CharField(choices=[('header', 'Header Banner'), ('sidebar', 'Sidebar Top'), ('in_article', 'In-Article (Article ke beech mein)')], max_length=20)),
                ('ad_type', models.CharField(choices=[('brand', 'Brand Collab (Image + Link)'), ('google', 'Google AdSense (Script)')], max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Brand ad image upload karein', null=True, upload_to='ads/')),
                ('url', models.URLField(blank=True, help_text='Brand ki website ka link', null=True)),
                ('google_ad_code', models.TextField(blank=True, help_text='Google Adsense ka HTML snippet yahan paste karein', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
