# Generated by Django 6.0.3 on 2026-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Job ka title (e.g., Senior Reporter)', max_length=200)),
                ('location', models.CharField(help_text='e.g., Remote, Tripura (Hybrid)', max_length=150)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=20)),
                ('description', models.TextField(help_text='Short description of the role')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck karein agar ye job ab available nahi hai')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
