# Generated by Django 6.0.3 on 2026-03-08 08:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(help_text='Full article content with rich text editor'),
        ),
    ]
