# Generated by Django 6.0.3 on 2026-03-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_editors_pick',
            field=models.BooleanField(default=False, help_text="Show in Editor's Picks section"),
        ),
    ]
