# Generated by Django 6.0.3 on 2026-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_tag_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_to_facebook',
            field=models.BooleanField(default=False, help_text='Tick karein Facebook par post karne ke liye'),
        ),
        migrations.AddField(
            model_name='article',
            name='post_to_telegram',
            field=models.BooleanField(default=False, help_text='Tick karein Telegram channel par post karne ke liye'),
        ),
        migrations.AddField(
            model_name='article',
            name='post_to_twitter',
            field=models.BooleanField(default=False, help_text='Tick karein Twitter (X) par post karne ke liye'),
        ),
    ]
