# Generated by Django 6.0.3 on 2026-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_post_to_facebook_article_post_to_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_top_story',
            field=models.BooleanField(default=False, help_text='Show in Top Stories section'),
        ),
    ]
