# Generated by Django 6.0.3 on 2026-03-12 20:00

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_is_top_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Tick if this is a Live Blog/Live Update article'),
        ),
        migrations.CreateModel(
            name='LiveUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Optional short title for this update', max_length=255, null=True)),
                ('content', tinymce.models.HTMLField(help_text='Update ka content (images, text, embeds)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Har update ka exact time')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_updates', to='news.article')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
