# Generated by Django 6.0.3 on 2026-03-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_article_is_live_liveupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='newsletter_sent',
            field=models.BooleanField(default=False, help_text='Tick ho jayega jab subscribers ko email bhej diya jayega'),
        ),
    ]
