# Generated by Django 6.0.3 on 2026-03-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article_newsletter_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='push_sent',
            field=models.BooleanField(default=False, help_text='Tick ho jayega jab push notification bhej diya jayega'),
        ),
    ]
