# Generated by Django 6.0.3 on 2026-03-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_article_push_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_web_story',
            field=models.BooleanField(default=False, help_text='Tick karein agar is article ko Web Stories (Shorts) mein dikhana hai'),
        ),
        migrations.AddField(
            model_name='article',
            name='web_story_created_at',
            field=models.DateTimeField(blank=True, help_text='Story banne ka time (24h expiry ke liye)', null=True),
        ),
    ]
