import uuid
from django.db import models
from django.utils.text import slugify
from tinymce.models import HTMLField
from core.models import BaseModel
from users.models import User
from django.utils import timezone


class Category(BaseModel):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=120, unique=True, blank=True)

    class Meta:
        verbose_name_plural = "Categories"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class Author(BaseModel):
    """
    Agar koi user author hai toh uski extra details. (author.js ke mutabiq)
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='author_profile')
    slug = models.SlugField(max_length=160, unique=True, blank=True)
    role = models.CharField(max_length=100, help_text="e.g. Senior Tech Reporter")
    twitter_url = models.URLField(blank=True, null=True)
    linkedin_url = models.URLField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.user.name) or f'author-{self.user_id}'
            slug_candidate = base_slug
            while Author.objects.filter(slug=slug_candidate).exclude(pk=self.pk).exists():
                slug_candidate = f"{base_slug}-{uuid.uuid4().hex[:6]}"
            self.slug = slug_candidate
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.name
    


class Tag(BaseModel):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=70, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class Article(BaseModel):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=300, unique=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='articles')
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, related_name='articles')
    
    # External sources (e.g. BBC News, TechCrunch)
    source_name = models.CharField(max_length=100, blank=True, null=True)
    source_url = models.URLField(max_length=500, blank=True, null=True, help_text="Original article link")
    is_imported = models.BooleanField(default=False, help_text="Flag to identify auto-imported articles")
    original_title = models.CharField(max_length=500, blank=True, null=True, help_text="Original source title")
    original_content = models.TextField(blank=True, null=True, help_text="Raw scraped content for reference")
    meta_description = models.CharField(max_length=160, blank=True, null=True, help_text="SEO Meta Description generated by AI")
    
    description = models.TextField(help_text="Short excerpt for homepage")
    # content = models.TextField(help_text="Full article content")
    content = HTMLField(help_text="Full article content with rich text editor")
    
    featured_image = models.ImageField(upload_to='articles/images/', blank=True, null=True)
    
    # ── Writer Evidence / Supporting Document ──
    # Ye field sirf verified writers ke submissions ke liye hai.
    # Editorial team is document ko review karta hai — yeh publicly visible nahi hota.
    supporting_document = models.FileField(
        upload_to='articles/evidence/',
        blank=True,
        null=True,
        verbose_name="Evidence",
        help_text="Writer ka supporting evidence document (PDF, image, video, etc.) — sirf editorial team ke liye"
    )
    writer_notes = models.TextField(
        blank=True,
        null=True,
        help_text="Writer ki taraf se editorial team ke liye additional notes (e.g. source context, confidentiality notice)"
    )
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    published_at = models.DateTimeField(blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name='articles', blank=True)
    # Frontend flags & stats
    views = models.PositiveIntegerField(default=0)
    is_featured = models.BooleanField(default=False, help_text="Manual Override: Large header me dikhane ke liye. (Default: System automatic recent posts pick karega)")
    is_trending = models.BooleanField(default=False, help_text="Manual Override: Force show in Trending. (Default: System top views wali recent posts ko trend karega)")
    is_breaking = models.BooleanField(default=False, help_text="Breaking News Ticker. (Dhyan rakhein: Ye 12 ghante baad automatically expire ho jayegi)")
    is_editors_pick = models.BooleanField(default=False, help_text="Show in Editor's Picks section (Ye purely manual hai)")
    is_top_story = models.BooleanField(default=False, help_text="Manual Override: Top Stories me dikhane ke liye. (Default: System automatically highest views wale pick karega)")
    is_live = models.BooleanField(default=False, help_text="Tick if this is a Live Blog/Live Update article")
    is_web_story = models.BooleanField(default=False, help_text="Tick karein agar is article ko Web Stories (Shorts) mein dikhana hai (Auto-expires in 24h)")
    web_story_created_at = models.DateTimeField(blank=True, null=True, help_text="Story banne ka time (24h expiry ke liye)")
    post_to_facebook = models.BooleanField(default=False, help_text="Tick karein Facebook par post karne ke liye")
    post_to_twitter = models.BooleanField(default=False, help_text="Tick karein Twitter (X) par post karne ke liye")
    post_to_telegram = models.BooleanField(default=False, help_text="Tick karein Telegram channel par post karne ke liye")
    newsletter_sent = models.BooleanField(default=False, help_text="Tick ho jayega jab subscribers ko email bhej diya jayega")
    push_sent = models.BooleanField(default=False, help_text="Tick ho jayega jab push notification bhej diya jayega")

    class Meta:
        indexes = [
            models.Index(fields=['status', '-published_at'], name='news_article_status_pub_idx'),
            models.Index(fields=['status', 'is_breaking', '-published_at'], name='news_article_breaking_idx'),
            models.Index(fields=['status', 'is_trending', '-views', '-published_at'], name='news_article_trending_idx'),
            models.Index(fields=['status', 'is_top_story', '-views', '-published_at'], name='news_article_top_story_idx'),
            models.Index(fields=['status', 'is_web_story', '-web_story_created_at'], name='news_article_story_idx'),
            models.Index(fields=['category', 'status', '-published_at'], name='news_article_category_idx'),
            models.Index(fields=['author', 'status', '-published_at'], name='news_article_author_idx'),
        ]

    def save(self, *args, **kwargs):
        # ── 1. Slug Generation ────────────────────────────────────────────────
        # Rule: generate slug ONLY when it is empty/blank.
        # Once a slug is set, we NEVER change it automatically — changing slugs
        # breaks existing URLs, social shares, and Google rankings.
        if not self.slug:
            # Truncate title to leave room for a potential "-xxxxxx" suffix
            # (slug field max_length=300, so base can be max 293 chars)
            raw_slug = slugify(self.title or "")[:293]

            # Fallback: if title is blank or entirely non-ASCII (slugify returns "")
            if not raw_slug:
                raw_slug = f"article-{uuid.uuid4().hex[:8]}"

            slug_candidate = raw_slug
            counter = 1
            # Keep incrementing until we find a unique slug in the DB
            while Article.objects.filter(slug=slug_candidate).exclude(pk=self.pk).exists():
                suffix = uuid.uuid4().hex[:6]
                slug_candidate = f"{raw_slug}-{suffix}"
                counter += 1
                if counter > 20:
                    # Safety valve — should never hit this in practice
                    slug_candidate = f"article-{uuid.uuid4().hex[:12]}"
                    break

            self.slug = slug_candidate

        # 2. WEB STORY 24-HOUR EXPIRY LOGIC
        if self.is_web_story and not self.web_story_created_at:
            # Jaise hi admin tick karke save karega, current time record ho jayega
            self.web_story_created_at = timezone.now()
        elif not self.is_web_story:
            # Agar admin ne tick hata diya, toh time clear kar do
            self.web_story_created_at = None

        if self.status == 'published' and not self.published_at:
            self.published_at = timezone.now()

        # 3. Clean up Scraped HTML (Database Bloat Optimization)
        if self.status == 'published' and self.original_content:
            self.original_content = None

        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class LiveUpdate(BaseModel):
    """
    Har ek live article ke andar chote-chote updates (jaise cricket commentary ya election count)
    """
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='live_updates')
    title = models.CharField(max_length=255, blank=True, null=True, help_text="Optional short title for this update")
    content = HTMLField(help_text="Update ka content (images, text, embeds)")
    timestamp = models.DateTimeField(default=timezone.now, help_text="Har update ka exact time")
    
    class Meta:
        ordering = ['-timestamp'] # Sabse naya update sabse upar dikhega
        indexes = [
            models.Index(fields=['article', '-timestamp'], name='news_live_article_time_idx'),
        ]

    def __str__(self):
        return f"Update for {self.article.title} at {self.timestamp}"
