# nginx/default.conf
server {
    listen 80;

    # 1. Django Static files serve karna
    location /static/ {
        alias /app/staticfiles/;
    }

    # 2. Django Media (Uploaded images/ads) serve karna
    location /media/ {
        alias /app/media/;
    }

    # 3. Baki sabhi requests ko sidha Django (backend) par proxy karna
    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}