# Generated by Django 6.0.3 on 2026-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('reporter', 'Reporter'), ('author', 'Author'), ('subscriber', 'Subscriber')], default='subscriber', max_length=20),
        ),
    ]
