# Generated by Django 6.0.2 on 2026-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField()),
                ('position', models.CharField(choices=[('header', 'Header Banner'), ('sidebar', 'Sidebar'), ('footer', 'Footer')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
