# Generated by Django 6.0.3 on 2026-03-29 18:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(help_text='e.g. Senior Tech Reporter', max_length=100)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(help_text='Short excerpt for homepage')),
                ('content', tinymce.models.HTMLField(help_text='Full article content with rich text editor')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in large header banner')),
                ('is_trending', models.BooleanField(default=False, help_text='Show in trending sidebar')),
                ('is_breaking', models.BooleanField(default=False, help_text='Show in breaking news ticker')),
                ('is_editors_pick', models.BooleanField(default=False, help_text="Show in Editor's Picks section")),
                ('is_top_story', models.BooleanField(default=False, help_text='Show in Top Stories section')),
                ('is_live', models.BooleanField(default=False, help_text='Tick if this is a Live Blog/Live Update article')),
                ('is_web_story', models.BooleanField(default=False, help_text='Tick karein agar is article ko Web Stories (Shorts) mein dikhana hai')),
                ('web_story_created_at', models.DateTimeField(blank=True, help_text='Story banne ka time (24h expiry ke liye)', null=True)),
                ('post_to_facebook', models.BooleanField(default=False, help_text='Tick karein Facebook par post karne ke liye')),
                ('post_to_twitter', models.BooleanField(default=False, help_text='Tick karein Twitter (X) par post karne ke liye')),
                ('post_to_telegram', models.BooleanField(default=False, help_text='Tick karein Telegram channel par post karne ke liye')),
                ('newsletter_sent', models.BooleanField(default=False, help_text='Tick ho jayega jab subscribers ko email bhej diya jayega')),
                ('push_sent', models.BooleanField(default=False, help_text='Tick ho jayega jab push notification bhej diya jayega')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.tag')),
            ],
        ),
        migrations.CreateModel(
            name='LiveUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Optional short title for this update', max_length=255, null=True)),
                ('content', tinymce.models.HTMLField(help_text='Update ka content (images, text, embeds)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Har update ka exact time')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_updates', to='news.article')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('description', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('content', config='english', weight='C'), django.contrib.postgres.search.SearchConfig('english')), name='article_fts_gin_idx'),
        ),
    ]
