# Generated by Django 6.0.3 on 2026-04-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
    ]
