# Generated by Django 6.0.3 on 2026-04-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20260401_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='Flag to identify auto-imported articles'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original article link', max_length=500, null=True),
        ),
    ]
