# Generated by Django 6.0.3 on 2026-04-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_is_imported_article_source_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='article_fts_gin_idx',
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_breaking',
            field=models.BooleanField(default=False, help_text='Breaking News Ticker. (Dhyan rakhein: Ye 12 ghante baad automatically expire ho jayegi)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_editors_pick',
            field=models.BooleanField(default=False, help_text="Show in Editor's Picks section (Ye purely manual hai)"),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Manual Override: Large header me dikhane ke liye. (Default: System automatic recent posts pick karega)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_top_story',
            field=models.BooleanField(default=False, help_text='Manual Override: Top Stories me dikhane ke liye. (Default: System automatically highest views wale pick karega)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Manual Override: Force show in Trending. (Default: System top views wali recent posts ko trend karega)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_web_story',
            field=models.BooleanField(default=False, help_text='Tick karein agar is article ko Web Stories (Shorts) mein dikhana hai (Auto-expires in 24h)'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='news_article_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'is_breaking', '-published_at'], name='news_article_breaking_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'is_trending', '-views', '-published_at'], name='news_article_trending_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'is_top_story', '-views', '-published_at'], name='news_article_top_story_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'is_web_story', '-web_story_created_at'], name='news_article_story_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status', '-published_at'], name='news_article_category_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status', '-published_at'], name='news_article_author_idx'),
        ),
        migrations.AddIndex(
            model_name='liveupdate',
            index=models.Index(fields=['article', '-timestamp'], name='news_live_article_time_idx'),
        ),
    ]
