# Generated by Django 6.0.3 on 2026-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_article_id_alter_author_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Writer ka supporting evidence document (PDF, image, video, etc.) — sirf editorial team ke liye', null=True, upload_to='articles/evidence/'),
        ),
        migrations.AddField(
            model_name='article',
            name='writer_notes',
            field=models.TextField(blank=True, help_text='Writer ki taraf se editorial team ke liye additional notes (e.g. source context, confidentiality notice)', null=True),
        ),
    ]
