# Generated by Django 5.0.3 on 2026-04-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_supporting_document_article_writer_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Writer ka supporting evidence document (PDF, image, video, etc.) — sirf editorial team ke liye', null=True, upload_to='articles/evidence/', verbose_name='Evidence'),
        ),
    ]
