# Generated by Django 6.0.3 on 2026-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_supporting_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_to_facebook',
            field=models.BooleanField(default=True, help_text='Tick karein Facebook par post karne ke liye'),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_to_telegram',
            field=models.BooleanField(default=True, help_text='Tick karein Telegram channel par post karne ke liye'),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_to_twitter',
            field=models.BooleanField(default=True, help_text='Tick karein Twitter (X) par post karne ke liye'),
        ),
    ]
