# Generated by Django 6.0.3 on 2026-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activist_applicant',
            field=models.BooleanField(default=False, help_text='Has the subscriber applied to become an activist?'),
        ),
    ]
