# Generated by Django 6.0.3 on 2026-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_activist_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activist_approved',
            field=models.BooleanField(default=False, help_text='Is the user officially approved as a verified guest writer?'),
        ),
    ]
