# Generated by Django 6.0.3 on 2026-04-02 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('news', '0004_remove_article_article_fts_gin_idx_author_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'is_active', '-created_at'], name='inter_comment_article_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscriber',
            index=models.Index(fields=['is_active', 'created_at'], name='inter_newsletter_active_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['is_active', '-created_at'], name='inter_poll_active_idx'),
        ),
    ]
