server {
    listen 80;
    
    # --- ADD THIS LINE TO INCREASE UPLOAD LIMIT ---
    client_max_body_size 50M; 

    location / {
        proxy_pass http://backend:8000;
        # Yahan $host ko badal kar $http_host kar dein
        proxy_set_header Host $http_host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /sitemap.xml {
        proxy_pass http://backend:8000;
        # Yahan bhi $http_host kar dein
        proxy_set_header Host $http_host;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}