# Generated by Django 6.0.3 on 2026-03-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mobile_only', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
                ('title', models.CharField(help_text='Internal reference ke liye naam', max_length=150)),
                ('slot', models.CharField(choices=[('header', 'Header Banner'), ('sidebar', 'Sidebar Top'), ('in_article', 'In-Article (Article ke beech mein)')], max_length=20)),
                ('ad_type', models.CharField(choices=[('brand', 'Brand Collab (Image + Link)'), ('google', 'Google AdSense (Script)')], max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Brand ad image upload karein', null=True, upload_to='ads/')),
                ('url', models.URLField(blank=True, help_text='Brand ki website ka link', null=True)),
                ('google_ad_code', models.TextField(blank=True, help_text='Google Adsense ka HTML snippet yahan paste karein', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Mark if this query has been handled.')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Job ka title (e.g., Senior Reporter)', max_length=200)),
                ('location', models.CharField(help_text='e.g., Remote, City Name (Hybrid)', max_length=150)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=20)),
                ('description', models.TextField(help_text='Short description of the role')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck karein agar ye job ab available nahi hai')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga4_tracking_id', models.CharField(blank=True, help_text='Google Analytics 4 Measurement ID (e.g., G-XXXXXXXXXX) yahan daalein.', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
