# Generated by Django 6.0.3 on 2026-04-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advertisepage_advertiseoption'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['slot', 'is_active', '-priority', '-created_at'], name='core_ad_slot_active_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_resolved', '-created_at'], name='core_contact_resolved_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_active', '-created_at'], name='core_job_active_idx'),
        ),
    ]
