"""
Django settings for newshub_core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r61u%hhptjjyge3=rc@ldeh!kkao6m2=fkq411l25ioda7k=%6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'django_filters',
    'rest_framework_simplejwt',
    'tinymce',
    'django.contrib.sites',   
    'django.contrib.sitemaps',
    



    'users',
    'news',
    'interactions',
    'core',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'newshub_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newshub_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



REST_FRAMEWORK = {
    # JWT Authentication setup
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Aapke frontend ke according pagination setup (6 articles per page)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 6,
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CORS_ALLOW_ALL_ORIGINS = True
AUTH_USER_MODEL = 'users.User'



# newshub_core/settings.py

# Print emails to the terminal for testing purposes
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@newshub.com'

# Change this to your frontend URL if you are hosting it elsewhere
FRONTEND_URL = 'http://127.0.0.1:5500'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),   # Token ab 5 minute ki jagah 7 din chalega
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30), # Refresh token 30 din tak chalega
    'AUTH_HEADER_TYPES': ('Bearer',),
}



TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'width': 'auto',
    'menubar': 'file edit view insert format tools table help',
    'plugins': 'advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount',
    'toolbar': 'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
    'custom_undo_redo_levels': 10,
}


# ==========================================
# CACHING SETUP (Industry Standard Redis)
# ==========================================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1", # Default Redis server address
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True, # Agar redis down ho toh app crash na ho, DB se data le le
        }
    }
}


GOOGLE_CLIENT_ID = 'YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com'

SITE_ID = 1


WEBPUSH_SETTINGS = {
    # Yahan apni PUBLIC key paste karein (Quotes " " ke andar)
    "VAPID_PUBLIC_KEY": "BI2oUZpcEccIW7PjnkjdgvxNxOro5G-abRV4Zn2jzVZDyseAtkaBF2OCYfqy1xHtdGEbjv4MXwza8rgJjAiKl1g", 
    
    # Yahan apni PRIVATE key paste karein (Quotes " " ke andar)
    "VAPID_PRIVATE_KEY": "rkZghoXeOTAzBKt6Nveq5-HiDubLJvfXSd0BbEDDclw", 
    
    # Yahan apna koi bhi admin email daal dein (e.g., admin@yoursite.com)
    "VAPID_ADMIN_EMAIL": "admin@dharmanagarlive.com" 
}

















# ==========================================
# JAZZMIN ADMIN DASHBOARD SETTINGS
# ==========================================

JAZZMIN_SETTINGS = {
    # Window/Tab title
    "site_title": "NewsHub Admin",
    
    # Login screen aur dashboard header ka naam
    "site_header": "NewsHub",
    
    # Sidebar ka brand name
    "site_brand": "NewsHub Dashboard",
    
    # Login screen ki welcome text
    "welcome_sign": "Welcome to NewsHub Admin Panel",
    
    # Copyright text at the bottom
    "copyright": "NewsHub by Dharmanagar Live",
    
    # Global search bar mein kin models ko search karna hai
    "search_model": ["news.Article", "users.User"],

    "custom_css": "css/admin_custom.css",

    # Top menu links
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Frontend Site", "url": "http://127.0.0.1:5500/index.html", "new_window": True},
    ],

    # Sidebar menu ko customize karna aur FontAwesome icons lagana
    "icons": {
        "auth": "fas fa-users-cog",
        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "news.Article": "fas fa-newspaper",
        "news.Category": "fas fa-list-alt",
        "news.Author": "fas fa-user-edit",
        "news.Tag": "fas fa-tags",
        "news.LiveUpdate": "fas fa-broadcast-tower",
        "interactions.Comment": "fas fa-comments",
        "interactions.Poll": "fas fa-poll",
        "interactions.Bookmark": "fas fa-bookmark",
        "interactions.NewsletterSubscriber": "fas fa-envelope-open-text",
        "interactions.PushSubscription": "fas fa-bell",
        "core.Advertisement": "fas fa-ad",
        "core.ContactMessage": "fas fa-envelope",
    },

    # Sidebar open rahega ya collapsed
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Related models ka dropdown kaisa dikhega
    "related_modal_active": True,
}
# ==========================================
# JAZZMIN THEME TWEAKS (MATCHING WEBSITE)
# ==========================================
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # 🔴 TWEAKED COLORS 🔴
    "brand_colour": "navbar-navy",        # Top left Logo background (Primary Navy)
    "navbar": "navbar-navy navbar-dark",  # Top header background (Primary Navy)
    "accent": "accent-danger",            # Hover & Accent elements (Secondary Red)
    "sidebar": "sidebar-light-navy",      # Sidebar background (Light layout with Navy active items)
    
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,       # Flat design modern lagta hai
    "theme": "default",                   # Default clean theme rakhein
    "dark_mode_theme": "darkly",          # Night mode
    "button_classes": {
        "primary": "btn-primary",         # Save buttons wagaira
        "secondary": "btn-danger",        # Secondary actions in Red
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}